### ISSUE TITLE
Access raw data

### ISSUE THREAD

**Issue by BarbaraTempl** [ISI-MIP/isipedia-text-generator#11]
If i click on "Access raw data", nothing happens - it reloads the website.

If i click on the sign next to the "Global ranking of countries" -> 
1) it download the .txt with the ranking and some kind of numbers. In case of drought: numbers refer to "affected land area" but which unit?

2) will the user ever have access to the raw data as well? Not only to the rankings.

**Comment by perrette** [comment]
Let's have this discussion somewhere else, and focus on country reports here.

**Comment by perrette** [comment]
Right we can have it here, I added a `website` label for the isssue.

**Comment by perrette** [comment]
I see. Not looked into that yet. Let me talk to CDLX.

**Comment by perrette** [comment]
Access plot data works fine: you get the data used to make the plot.
I don't know what raw data is supposed to mean. @matthiasmengel ?
The ranking data associated with the figure, as I download it, is:

`land-area-affected-by-drought-relative-changes_ISIMIP-projections_versus-temperature-change.txt`

`relative` means that the number as in % relative to reference period
(note the original unit are also % !! -- how confusing... -- we are talking of ridiculously small numbers in the reference period, so the numbers do not make sense)

See the related issue on ASANA: in my view the priority should be to forget about 'relative' changes and focus on 'absolute' (that means anomalies, i.e. simple difference w.r.t reference...) or raw numbers instead. Everything is in % anyways. That means, remove or at least inspect any variable with `rel` in their `{name}` in the templates. And also importantly, update the line-plots command to show absolute variables. I think we should also move to raw variables, but these variables need to be added. 

I think you should get familiar with all the variables present in the json files before doing any meaningful editing. 

Later on we will hopefully have less fancy variables (I hope with physical units such as mm/year or degrees C) instead of these % and % of %, but well, first things first.

**Comment by perrette** [comment]
I believe raw data should give access to esgf files, but the feature is not implemented yet, and this is not a priority (after a chat with jan a couple of weeks ago regarding these links).

**Comment by matthiasmengel** [comment]
My understanding is that we have two levels of "data behind plots to download". The processed data, which exactly reflects what is seen in the plot. Probably txt or csv. This should be priority for now. We will later, in collaboration with Jochen and the new ISIMIP data download platform, link to the unprocessed ISIMIP outputs, so the data currently available through ESGF.

**Comment by perrette** [comment]
Currently the `plot data` links to the full json files, and the `raw data` does nothing.

**Comment by perrette** [comment]
In fact, the `raw data` follows the `esgf_search_url` when it is defined.
The `plot_data` links to json files, which is good.

Issue solved.
